# Generated by Django 3.2.4 on 2021-07-16 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('name', models.CharField(choices=[('Samsung', 'Samsung'), ('Apple', 'Apple'), ('Huawei', 'Huawei'), ('Oppo', 'Oppo'), ('xiaomi', 'xiaomi'), ('Infinix', 'Infinix'), ('Nokia', 'Nokia'), ('Sony', 'Sony'), ('LG', 'LG'), ('HTC', 'HTC'), ('Lenovo', 'Lenovo'), ('Realme', 'Realme'), ('Honor', 'Honor'), ('ZTE', 'ZTE'), ('Vivo', 'Vivo')], max_length=100, verbose_name='Brand Name')),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug_dev', models.SlugField(blank=True, null=True)),
                ('modeldev', models.CharField(blank=True, max_length=100, null=True)),
                ('nameDev', models.CharField(max_length=320, verbose_name='Name')),
                ('networkDev', models.CharField(blank=True, max_length=500, null=True, verbose_name='Network')),
                ('announcedDev', models.CharField(blank=True, max_length=500, null=True, verbose_name='Announced')),
                ('statusDev', models.CharField(blank=True, max_length=500, null=True, verbose_name='Status')),
                ('dimensionsDev', models.CharField(blank=True, max_length=500, null=True, verbose_name='Device Dimensions')),
                ('wightDev', models.CharField(blank=True, max_length=500, null=True, verbose_name='Device Wight')),
                ('buildDev', models.CharField(blank=True, max_length=500, null=True, verbose_name='Build')),
                ('simDev', models.CharField(blank=True, max_length=500, null=True, verbose_name='Sim')),
                ('displayTypeDev', models.CharField(blank=True, max_length=500, null=True, verbose_name='Screen Type')),
                ('displaySizeDev', models.CharField(blank=True, max_length=500, null=True, verbose_name='Screen Size')),
                ('displayResDev', models.CharField(blank=True, max_length=500, null=True, verbose_name='Screen Resolution')),
                ('oSDev', models.CharField(blank=True, max_length=350, null=True, verbose_name='Android')),
                ('chipsetDev', models.CharField(blank=True, max_length=550, null=True, verbose_name='Chipset')),
                ('cPUDev', models.CharField(blank=True, max_length=500, null=True, verbose_name='CPU')),
                ('cardSlotDev', models.CharField(blank=True, max_length=500, null=True, verbose_name='Card Slot')),
                ('internalDev', models.CharField(blank=True, max_length=500, null=True, verbose_name='Device Storage')),
                ('mainCameraDev', models.CharField(blank=True, max_length=500, null=True, verbose_name='Main Camera')),
                ('main_camera_featuresDev', models.CharField(blank=True, max_length=550, null=True, verbose_name='Features Main Camera')),
                ('main_camera_videoDev', models.CharField(blank=True, max_length=550, null=True, verbose_name='Main Camera Video')),
                ('selfieCameraDev', models.CharField(blank=True, max_length=500, null=True, verbose_name='Selfie Camera')),
                ('selfie_camera_videoDev', models.CharField(blank=True, max_length=500, null=True, verbose_name='Selfie Camera Video')),
                ('loudspeakerDev', models.CharField(blank=True, max_length=500, null=True, verbose_name='Loudspeaker')),
                ('wlanDev', models.CharField(blank=True, max_length=500, null=True, verbose_name='WLAN')),
                ('bluetoothDev', models.CharField(blank=True, max_length=500, null=True, verbose_name='Bluetooth')),
                ('nfcDev', models.CharField(blank=True, max_length=500, null=True, verbose_name='NFC')),
                ('radioDev', models.CharField(blank=True, max_length=500, null=True, verbose_name='Radio')),
                ('usbDev', models.CharField(blank=True, max_length=500, null=True, verbose_name='USB')),
                ('sensorsDev', models.CharField(blank=True, max_length=500, null=True, verbose_name='Sensors')),
                ('batteryDev', models.CharField(blank=True, max_length=500, null=True, verbose_name='Battery Type')),
                ('priceDev', models.CharField(blank=True, max_length=500, null=True, verbose_name='Price')),
                ('imageDev', models.ImageField(blank=True, upload_to='Devices/Devices_Img/', verbose_name='Image Device')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app1.brand')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.color')),
            ],
        ),
        migrations.CreateModel(
            name='Spare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('model', models.CharField(blank=True, max_length=200, null=True, verbose_name='Model')),
                ('category', models.CharField(blank=True, choices=[('CompScreen', 'CompScreen'), ('Lcd', 'Lcd'), ('Touch', 'Touch'), ('SubBoard', 'SubBoard'), ('ChargingSocket', 'ChargingSocket'), ('HandfreeSocket', 'HandfreeSocket'), ('Board', 'Board'), ('Battery', 'Battery'), ('BackCamera', 'BackCamera'), ('SelfieCamera', 'SelfieCamera'), ('BackGlassCover', 'BackGlassCover'), ('Housing', 'Housing')], max_length=50, null=True)),
                ('name', models.CharField(max_length=320, verbose_name='Name')),
                ('quality', models.CharField(blank=True, choices=[('Original', 'Original'), ('HighCopy', 'HighCopy'), ('Copy', 'Copy')], max_length=50, null=True)),
                ('warranty', models.IntegerField(default=0, verbose_name='Warranty')),
                ('code', models.CharField(blank=True, max_length=320, null=True, verbose_name='Code')),
                ('image', models.ImageField(blank=True, upload_to='Spare/Spare_img/', verbose_name='Image Spare')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='Price')),
                ('new_or_not', models.BooleanField(default=False, verbose_name='Used Spare')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.brand')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.color')),
                ('device_main', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Device_sets', to='app1.device')),
                ('device_same', models.ManyToManyField(to='app1.Device', verbose_name='Work For Mobiles')),
            ],
        ),
    ]
