# Generated by Django 3.2.4 on 2021-07-16 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(choices=[('Samsung', 'Samsung'), ('Apple', 'Apple'), ('Huawei', 'Huawei'), ('Oppo', 'Oppo'), ('xiaomi', 'xiaomi'), ('Infinix', 'Infinix'), ('Nokia', 'Nokia'), ('Sony', 'Sony'), ('LG', 'LG'), ('HTC', 'HTC'), ('Lenovo', 'Lenovo'), ('Realme', 'Realme'), ('Honor', 'Honor'), ('ZTE', 'ZTE'), ('Vivo', 'Vivo'), ('Alcatel', 'Alcatel'), ('Asus', 'Asus'), ('Motorola', 'Motorola'), ('Acer', 'Acer')], max_length=100, verbose_name='Brand Name'),
        ),
        migrations.AlterField(
            model_name='device',
            name='color',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Color'),
        ),
    ]
