# Generated by Django 3.2.4 on 2021-07-06 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='DisplaySizeDev',
            new_name='displaySizeDev',
        ),
        migrations.RenameField(
            model_name='device',
            old_name='DisplayTypeDev',
            new_name='displayTypeDev',
        ),
        migrations.RenameField(
            model_name='device',
            old_name='NameDev',
            new_name='nameDev',
        ),
        migrations.AddField(
            model_name='device',
            name='announcedDev',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Announced'),
        ),
        migrations.AddField(
            model_name='device',
            name='batteryDev',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Battery Type'),
        ),
        migrations.AddField(
            model_name='device',
            name='bluetoothDev',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bluetooth'),
        ),
        migrations.AddField(
            model_name='device',
            name='buildDev',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Build'),
        ),
        migrations.AddField(
            model_name='device',
            name='cPUDev',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='CPU'),
        ),
        migrations.AddField(
            model_name='device',
            name='cardSlotDev',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Card Slot'),
        ),
        migrations.AddField(
            model_name='device',
            name='chipsetDev',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Chipset'),
        ),
        migrations.AddField(
            model_name='device',
            name='dimensionsDev',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Device Dimensions'),
        ),
        migrations.AddField(
            model_name='device',
            name='displayResDev',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Screen Resolution'),
        ),
        migrations.AddField(
            model_name='device',
            name='imageDev',
            field=models.ImageField(blank=True, upload_to='Devices/Devices_Img/', verbose_name='Image Device'),
        ),
        migrations.AddField(
            model_name='device',
            name='internalDev',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Device Storage'),
        ),
        migrations.AddField(
            model_name='device',
            name='loudspeakerDev',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Loudspeaker'),
        ),
        migrations.AddField(
            model_name='device',
            name='mainCameraDev',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Main Camera'),
        ),
        migrations.AddField(
            model_name='device',
            name='main_camera_featuresDev',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Features Main Camera'),
        ),
        migrations.AddField(
            model_name='device',
            name='main_camera_videoDev',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Main Camera Video'),
        ),
        migrations.AddField(
            model_name='device',
            name='networkDev',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Network'),
        ),
        migrations.AddField(
            model_name='device',
            name='nfcDev',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='NFC'),
        ),
        migrations.AddField(
            model_name='device',
            name='oSDev',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Android'),
        ),
        migrations.AddField(
            model_name='device',
            name='priceDev',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Price'),
        ),
        migrations.AddField(
            model_name='device',
            name='radioDev',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Radio'),
        ),
        migrations.AddField(
            model_name='device',
            name='selfieCameraDev',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Selfie Camera'),
        ),
        migrations.AddField(
            model_name='device',
            name='selfie_camera_videoDev',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Selfie Camera Video'),
        ),
        migrations.AddField(
            model_name='device',
            name='sensorsDev',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sensors'),
        ),
        migrations.AddField(
            model_name='device',
            name='simDev',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Sim'),
        ),
        migrations.AddField(
            model_name='device',
            name='statusDev',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='device',
            name='usbDev',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='USB'),
        ),
        migrations.AddField(
            model_name='device',
            name='wightDev',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Device Wight'),
        ),
        migrations.AddField(
            model_name='device',
            name='wlanDev',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='WLAN'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(choices=[('Samsung', 'Samsung'), ('Apple', 'Apple'), ('Huawei', 'Huawei'), ('Oppo', 'Oppo'), ('xiaomi', 'xiaomi'), ('Infinix', 'Infinix'), ('Nokia', 'Nokia'), ('Sony', 'Sony'), ('LG', 'LG'), ('HTC', 'HTC'), ('Lenovo', 'Lenovo'), ('Realme', 'Realme'), ('Honor', 'Honor')], max_length=100, verbose_name='اسم البراند'),
        ),
    ]
