# Generated by Django 3.2.4 on 2021-07-16 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20210716_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='img_dev_full_1',
            field=models.ImageField(blank=True, upload_to='Devices/Devices_full_pic/', verbose_name='Image Device'),
        ),
        migrations.AddField(
            model_name='device',
            name='img_dev_full_2',
            field=models.ImageField(blank=True, upload_to='Devices/Devices_full_pic/', verbose_name='Image Device'),
        ),
    ]
