# Generated by Django 3.2.4 on 2021-07-06 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20210706_2258'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('model', models.CharField(blank=True, max_length=200, null=True, verbose_name='Model')),
                ('category', models.CharField(blank=True, choices=[('CompScreeb', 'CompScreeb'), ('Lcd', 'Lcd'), ('Touch', 'Touch'), ('SubBoard', 'SubBoard'), ('ChargingSocket', 'ChargingSocket'), ('HandfreeSocket', 'HandfreeSocket'), ('Board', 'Board'), ('Battery', 'Battery'), ('BackCamera', 'BackCamera'), ('SelfieCamera', 'SelfieCamera'), ('BackGlassCover', 'BackGlassCover'), ('Housing', 'Housing')], max_length=50, null=True)),
                ('name', models.CharField(max_length=320, verbose_name='Name')),
                ('quality', models.CharField(blank=True, choices=[('Original', 'Original'), ('HighCopy', 'HighCopy'), ('Copy', 'Copy')], max_length=50, null=True)),
                ('warranty', models.IntegerField(default=0, verbose_name='Warranty')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.brand')),
                ('device_main', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Device_sets', to='app1.device')),
                ('device_same', models.ManyToManyField(to='app1.Device', verbose_name='Work For Mobiles')),
            ],
        ),
    ]
