# Generated by Django 3.2.4 on 2021-07-08 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_spare'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='spare',
            name='code',
            field=models.CharField(blank=True, max_length=320, null=True, verbose_name='Code'),
        ),
        migrations.AddField(
            model_name='spare',
            name='image',
            field=models.ImageField(blank=True, upload_to='Spare/Spare_img/', verbose_name='Image Spare'),
        ),
        migrations.AddField(
            model_name='spare',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='Price'),
        ),
    ]
